### ISSUE TITLE
类型转换异常

### ISSUE THREAD

**Issue by mapengfei00099** [tencentyun/tls-sig-api-java#1]
Exception in thread "main" java.lang.ClassCastException: org.bouncycastle.openssl.PEMKeyPair cannot be cast to org.bouncycastle.asn1.pkcs.PrivateKeyInfo
	at com.tls.tls_sigature.tls_sigature.GenTLSSignature(tls_sigature.java:82)
	at com.tls.tls_sigature.tls_sigature.GenTLSSignatureEx(tls_sigature.java:282)
	at com.tim.util.SigUtil.GenSignature(SigUtil.java:87)
	at com.tim.util.SigUtil.GetSignature(SigUtil.java:47)
	at com.tim.restapi.HttpPost.doPost(HttpPost.java:20)

**Comment by okhowang** [comment]
是否传入的私钥格式不对
这里需要的是pkcs8

**Comment by mapengfei00099** [comment]
根据文档
http://www.bouncycastle.org/docs/pkixdocs1.5on/org/bouncycastle/openssl/PEMKeyPair.html
使用getPrivateKeyInfo()  获取到了正确的PrivateKeyInfo
具体代码如下：

         
                ```Reader reader = new CharArrayReader(privStr.toCharArray());
		JcaPEMKeyConverter converter = new JcaPEMKeyConverter();
		PEMParser parser = new PEMParser(reader);
		Object obj = parser.readObject();
		parser.close();
		PrivateKey privKeyStruct = null;
		if(obj instanceof PEMKeyPair){
			PEMKeyPair keyPair = (PEMKeyPair)obj;
			 privKeyStruct = converter.getPrivateKey(keyPair.getPrivateKeyInfo());
		}else {
			privKeyStruct = converter.getPrivateKey((PrivateKeyInfo)obj);

		}
             ```

**Comment by weijunyi** [comment]
直接在控制台上下载的私钥可以直接使用，代码里面我们没有做这种兼容，
